### ISSUE TITLE
Similar package

### ISSUE THREAD

**Issue by jlangston99** [hglanz/LinearModel-RViz-Summer2019#1]
@hglanz 
Please take a look at ggPredict.R file. ggPredict is a function inside the ggiraphExtra package that does most of what we want in our package. It can do a:
- Simple linear regression line.
- Regression model with one categorical variable and one quantitative variable. 
- Regression model with one categorical variable, one quantitative variable, and the interaction term.
- Regression model with one quantitative variable and the interaction with a categorical variable.

It can not plot models with 2+ order polynomials, so I see room for improvement there. It takes a model as the only necessary parameter. I don't have a problem with this, but I think it should be an option for a user to pass their data, categorical variable, quantitative variable, and response variable or a model into the functions and have get the same result. 

What do you think the ggPredict function, and how it compares to what we want to create? What other improvements do you think we can make on the ggPredict function?

**Comment by hglanz** [comment]
@jlangston99 this does indeed sound like a lot of what we want to do. Could you find and provide a link to a small, reproducible example of using the ggPredict() function for each of your bulleted items?...perhaps with the iris dataset or something? Or create it yourself?

I think I'll be able to judge it better with this in hand :) Thanks!

**Comment by jlangston99** [comment]
@hglanz look at the ggPredict.R file in the R folder.

**Comment by hglanz** [comment]
@jlangston99 Sorry if I missed those the first time. This is pretty great, but I agree with your assessment and maybe a bit more:

- It would be nice to be able to pass the objects that you mentioned instead of the model object.
- It would be nice to be able to handle models that are polynomial in the quantitative variable
- I tried playing around with the "interactive = TRUE" option. It's awesome! However, I can envision an extra option, say "stickylabels = TRUE" that let's the user hover on points or the lines to see the information but clicking makes the info stay displayed. This would be a big help for being able to save/export the graphs with certain information displayed.

What do you think?

P.S. I will be out of town without email until Wednesday, but I think these things should be enough to pursue for now. Please feel free to continue posting thoughts and questions here!
